---
title: "Regression Analysis"
author: "Embon, Barttfeld & Solovey"
date: "8/9/2021"
output: html_document
---

## Levantar datos
                                 
```{r levantar datos, echo=TRUE}

root <- rprojroot::is_rstudio_project
basename(getwd())               

####### data frames with filters already applied
filepath <- root$find_file("Data/All_exp_exclusion_criteria/df_total.Rda")
load(file= filepath)

source(root$find_file("Analysis/AuxiliaryFunctions/DataFrame_Filtered_already_applied.R"))
DF_list <- DataFrame_Filtered_already_applied(df_total)

d.sin.normalizar.solo.FyM <- DF_list$d


###########################
### Regression Analysis ###
###########################

### lineas para hacer regresion 

d1 <- d.sin.normalizar.solo.FyM

d1$aq.norm <- (d1$aq - mean(d1$aq))/ sd(d1$aq)

d1$mc.norm <- (d1$mc - mean(d1$mc))/ sd(d1$mc)

d1$m_c.norm <- (d1$m_c - mean(d1$m_c))/ sd(d1$m_c)
d1$sd_c.norm <- (d1$sd_c - mean(d1$sd_c))/ sd(d1$sd_c)

d1$edad.norm <- (d1$edad - mean(d1$edad))/ sd(d1$edad)
d1$tr_d.norm <- (d1$tr_d - mean(d1$tr_d))/ sd(d1$tr_d)
d1$tr_c.norm <- (d1$tr_c - mean(d1$tr_c))/ sd(d1$tr_c)

d1[d1 == "Masculino"] <- "1"
d1[d1 == "Femenino"] <- "0"
d1$Im <- as.integer(d1$Im)

```

##### Empiezo a correr modelos de regresiones

## Modelo 1
```{r modelo 1, echo=TRUE}

a=lm(m_c.norm ~ aq.norm +
       Im +
       edad.norm+
       es +
       aq.norm: Im,
     data = d1) 
summary(a)

```
## Modelo 2

```{r Modelo 2, echo=TRUE}

a=lm(tr_d.norm ~ aq.norm +
       Im +
       aq.norm: Im,
     data = d1) 
summary(a)

```
## Modelo 3

```{r Modelo 3, echo=TRUE}

a=lm(tr_d.norm ~ aq.norm +
       Im +
       edad.norm+
       aq.norm: Im+
       aq.norm:edad.norm+
       Im:edad.norm,
     data = d1) 
summary(a)

```

## Modelo 4

```{r Modelo 4, echo=TRUE}

a=lm(tr_d.norm ~ aq.norm +
       Im +
       edad.norm+
       es +
       aq.norm: Im+
       aq.norm:edad.norm+
       Im:edad.norm+
       es:aq.norm,
     data = d1) 
summary(a)

```
## Modelo 5 

```{r Modelo 5, echo=TRUE}

a=lm(tr_d.norm ~ aq.norm +
       Im +
       edad.norm+
       aq.norm: Im,
       #aq.norm:edad.norm+
       #Im:edad.norm,
     data = d1) 
summary(a)

```
## Modelo 6 (este es el modelo final que usariamos)

```{r Modelo 6, echo=TRUE}

a=lm(tr_d.norm ~ aq.norm +
       Im +
       edad.norm+
       aq.norm: Im+
       aq.norm:edad.norm,
       #Im:edad.norm,
     data = d1) 
summary(a)

```

## Modelo 7 - separado para masculinos y femeninos

```{r Modelo 7, echo=TRUE}
d.f <- d1[d1$Im== "0",]

a.f =lm(tr_d.norm ~ aq.norm +
       #Im +
       edad.norm+
       #aq.norm: Im+
       aq.norm:edad.norm,
     data = d.f) 
summary(a.f)

d.m <- d1[d1$Im== "1",]

a.m =lm(tr_d.norm ~ aq.norm +
       #Im +
       edad.norm+
       #aq.norm: Im+
       aq.norm:edad.norm,
     data = d.m) 
summary(a.m)
```